version: '3'
services:
  app:
    container_name: flood-control
    image: rituparnshukla/flood-control:latest
    ports:
      - "8090:8090"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6389:6379"


