version: '3'
services:
  app1:
    container_name: flood-control-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8090
    ports:
      - "8090:8090"
    depends_on:
      - redis

  app2:
    container_name: flood-control-2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8091
    ports:
      - "8091:8091"
    depends_on:
      - redis

  app3:
    container_name: flood-control-3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8092
    ports:
      - "8092:8092"
    depends_on:
      - redis

  nginx:
    container_name: nginx-load-balancer
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
  redis:
    image: redis:latest
    ports:
      - "6389:6379"